defmodule AshA2A.TaskFailedStateTest do
  @moduledoc """
  Real, unmocked proof that a real `A2A.Agent` GenServer, generated by
  `AshA2A.Agent` over a genuinely-forbidding Ash resource, drives a real
  task through `:submitted -> :working -> :failed` -- not just `:completed`,
  which `test/ash_a2a_test.exs` and `test/ash_a2a_rap_battle_integration_test.exs`
  already cover.

  Assignment #6 (real task state machine transition to `:failed`). Existing
  coverage of the forbidden-dispatch error class
  (`test/ash_a2a_test.exs:101-137`) calls `AshA2A.Dispatcher.dispatch/3`
  directly -- bypassing the real `A2A.Agent`/`A2A.Agent.Runtime` state
  machine entirely, so nothing in this repo's test suite previously proved
  that a real, supervised `A2A.Agent` process actually reaches the real
  `:failed` terminal state. This file closes that gap using only real,
  already-existing machinery:

  - `AshA2A.Test.Fixture.Locked` / `LockedDomain` (`test/support/fixture.ex`)
    -- a real `Ash.Resource` + `Ash.Policy.Authorizer` that always forbids.
  - `AshA2A.Test.Fixture.LockedAgent` (`test/support/failing_task_fixture.ex`)
    -- a real `A2A.Agent` GenServer built with `use AshA2A.Agent` over
    `Locked`.
  - `AshA2A.Test.AgentSupervisorCase.start_supervised_agents!/2` -- the
    existing real `A2A.AgentSupervisor.start_link/1` bootstrap helper.
  - `AshA2A.Test.MessageHelpers.data_message/1` -- the existing real
    `A2A.Message.new_user/1` builder.

  No `Mock`/`mox`/`patch`/`monkeypatch` anywhere in this file.
  """

  use ExUnit.Case, async: true

  alias AshA2A.Test.AgentSupervisorCase
  alias AshA2A.Test.Fixture.LockedAgent
  alias AshA2A.Test.MessageHelpers

  test "a real forbidden dispatch drives a real A2A.Agent task through :submitted -> :working -> :failed" do
    {_sup, _registry} = AgentSupervisorCase.start_supervised_agents!(__MODULE__, [LockedAgent])

    agent_pid = GenServer.whereis(LockedAgent)
    assert is_pid(agent_pid)

    message = MessageHelpers.data_message(%{})

    # `LockedAgent.call/3` drives the message through the REAL
    # `A2A.Agent.Runtime.process_message/5` -> `run_task/4` path
    # (`~/xaas/deps/a2a/lib/a2a/agent/runtime.ex:22-25,62-79`), which
    # unconditionally transitions the freshly-`Task.new/1`-created task
    # (born `:submitted`, `~/xaas/deps/a2a/lib/a2a/task.ex:69-77`) to
    # `:working` BEFORE calling `LockedAgent.handle_message/2` ==
    # `AshA2A.Agent.__dispatch__/3` == `AshA2A.Dispatcher.dispatch/5`. The
    # real `Ash.Policy.Authorizer` denial on `Locked`'s always-forbidding
    # policy surfaces as a real `%Ash.Error.Forbidden.Policy{}` with
    # `class: :forbidden`, which `AshA2A.Dispatcher.to_reply/1`
    # (`lib/ash_a2a/dispatcher.ex:553-556`) maps to a real
    # `{:error, "forbidden: " <> _}` reply tuple -- exactly the
    # `{:error, reason}` shape `A2A.Agent.Runtime.handle_reply/2`
    # (`~/xaas/deps/a2a/lib/a2a/agent/runtime.ex:99-103`) transitions to
    # `:failed` for real, with a real `A2A.Message.new_agent/1` error
    # message appended to task history.
    assert {:ok, task} = LockedAgent.call(agent_pid, message)

    assert task.status.state == :failed

    # `A2A.Task.terminal?/1` (`~/xaas/deps/a2a/lib/a2a/task.ex:29-37`) --
    # real terminality check, not a hand-rolled duplicate of its state list.
    assert A2A.Task.terminal?(task)

    # The real error message `handle_reply/2` builds
    # (`Message.new_agent("Error: " <> inspect(reason))`) is really stored
    # on the real task's `status.message` by `A2A.Agent.State.transition/3`
    # (`~/xaas/deps/a2a/lib/a2a/agent/state.ex:21-23` --
    # `A2A.Task.Status.new(new_state, message)`) -- not merely a bare
    # `:failed` atom with no accompanying, inspectable record of what
    # failed. `history` itself stays exactly `[user_message]`: unlike the
    # `:completed`/`:input_required` branches of `handle_reply/2`
    # (`~/xaas/deps/a2a/lib/a2a/agent/runtime.ex:83-98`), the real
    # `:error` branch (lines 99-103) never appends `error_msg` to
    # `task.history` -- only to `status.message`.
    assert [%A2A.Message{role: :user}] = task.history

    assert %A2A.Message{role: :agent} = agent_error_msg = task.status.message
    [%A2A.Part.Text{text: error_text}] = agent_error_msg.parts
    assert error_text =~ "Error:"
    assert error_text =~ "forbidden"

    # A real terminal :failed task is really not cancelable -- proves the
    # :failed state genuinely feeds back into `A2A.Agent`'s own cancel
    # guard (`~/xaas/deps/a2a/lib/a2a/agent.ex:308`), not just a status
    # label with no other real behavioral consequence.
    assert {:error, :not_cancelable} = LockedAgent.cancel(agent_pid, task.id)

    # Fetching the same task back by id from the real agent process
    # confirms the :failed state was really persisted into `A2A.Agent.State`
    # (`State.put_task/2` in the real `handle_call({:message, ...})` clause),
    # not just returned transiently in the `call/3` reply.
    assert {:ok, %A2A.Task{status: %A2A.Task.Status{state: :failed}}} =
             LockedAgent.get_task(agent_pid, task.id)
  end
end
