defmodule AshA2A.Chicago.Fixtures.Authority do
  @moduledoc """
  Real fixtures for the RFC-SA2A-002 authority courts
  (`AshA2A.Chicago.Courts.AuthorityNonImplication`,
  `AshA2A.Chicago.Courts.GrantLifecycle`).

    * `Ledger` -- an ETS resource every consequential action writes one row
      to. It is the independent post-state reader: a court asks
      `recorded?/1` (a real `Ash.read!/1`), never the actuator's return value.
    * `Probe` -- `:actuate` (`:external_do`), `:mutate` (`:change`) and
      `:peek` (`:observe`) skills.
    * `Vault` -- a DIFFERENT resource that also exposes a skill named
      `:actuate` (`:external_do`), so capability-name substitution across
      agents is testable.
    * `ProbeAgent` / `VaultAgent` -- real `A2A.Agent` GenServers generated by
      `use AshA2A.Agent`; courts start them under unique names.

  Compiled in every environment so the courts can run from
  `mix ash_a2a.chicago`; nothing here references `test/support`.
  """

  alias AshA2A.Chicago.Fixtures.Authority.Ledger

  @doc "True when a consequential action really wrote a ledger row for `nonce`."
  @spec recorded?(String.t()) :: boolean()
  def recorded?(nonce) when is_binary(nonce), do: rows(nonce) != []

  @doc "Every ledger row written for `nonce`, read through a real `Ash.read!/1`."
  @spec rows(String.t()) :: [struct()]
  def rows(nonce) when is_binary(nonce) do
    Ledger
    |> Ash.read!(authorize?: false)
    |> Enum.filter(&(&1.nonce == nonce))
  end

  @doc false
  @spec record!(String.t() | nil, String.t()) :: {:ok, map()}
  def record!(nonce, capability) when is_binary(nonce) do
    Ledger
    |> Ash.Changeset.for_create(:record, %{nonce: nonce, capability: capability})
    |> Ash.create!(authorize?: false)

    {:ok, %{recorded: true, nonce: nonce, capability: capability}}
  end

  def record!(nil, _capability), do: {:error, "nonce is required"}
end

defmodule AshA2A.Chicago.Fixtures.Authority.Domain do
  @moduledoc "Real Ash domain for the authority-court fixtures."
  use Ash.Domain, validate_config_inclusion?: false

  resources do
    resource(AshA2A.Chicago.Fixtures.Authority.Ledger)
    resource(AshA2A.Chicago.Fixtures.Authority.Probe)
    resource(AshA2A.Chicago.Fixtures.Authority.Vault)
  end
end

defmodule AshA2A.Chicago.Fixtures.Authority.Ledger do
  @moduledoc "Consequence ledger: one row per real actuation (independent post-state)."
  use Ash.Resource,
    domain: AshA2A.Chicago.Fixtures.Authority.Domain,
    data_layer: Ash.DataLayer.Ets

  attributes do
    uuid_primary_key(:id)
    attribute(:nonce, :string, allow_nil?: false, public?: true)
    attribute(:capability, :string, allow_nil?: false, public?: true)
  end

  actions do
    defaults([:read])

    create :record do
      accept([:nonce, :capability])
    end
  end
end

defmodule AshA2A.Chicago.Fixtures.Authority.Probe do
  @moduledoc "Consequence-bearing probe resource for the authority courts."
  use Ash.Resource,
    domain: AshA2A.Chicago.Fixtures.Authority.Domain,
    data_layer: Ash.DataLayer.Ets,
    extensions: [AshA2A]

  alias AshA2A.Chicago.Fixtures.Authority

  attributes do
    uuid_primary_key(:id)
  end

  actions do
    action :actuate, :map do
      argument(:nonce, :string, allow_nil?: true)
      run(fn input, _context -> Authority.record!(input.arguments[:nonce], "probe.actuate") end)
    end

    action :mutate, :map do
      argument(:nonce, :string, allow_nil?: true)
      run(fn input, _context -> Authority.record!(input.arguments[:nonce], "probe.mutate") end)
    end

    action :peek, :map do
      run(fn _input, _context -> {:ok, %{peeked: true}} end)
    end
  end

  a2a do
    skill(:actuate, :actuate, consequence: :external_do)
    skill(:mutate, :mutate, consequence: :change)
    skill(:peek, :peek, consequence: :observe)
  end
end

defmodule AshA2A.Chicago.Fixtures.Authority.Vault do
  @moduledoc """
  A second resource whose `:actuate` skill shares its selector name with
  `Probe.actuate` but is a different capability (different canonical id).
  """
  use Ash.Resource,
    domain: AshA2A.Chicago.Fixtures.Authority.Domain,
    data_layer: Ash.DataLayer.Ets,
    extensions: [AshA2A]

  alias AshA2A.Chicago.Fixtures.Authority

  attributes do
    uuid_primary_key(:id)
  end

  actions do
    action :actuate, :map do
      argument(:nonce, :string, allow_nil?: true)
      run(fn input, _context -> Authority.record!(input.arguments[:nonce], "vault.actuate") end)
    end
  end

  a2a do
    skill(:actuate, :actuate, consequence: :external_do)
  end
end

defmodule AshA2A.Chicago.Fixtures.Authority.ProbeAgent do
  @moduledoc "Real `A2A.Agent` over `AshA2A.Chicago.Fixtures.Authority.Probe`."
  use AshA2A.Agent,
    resource_or_domain: AshA2A.Chicago.Fixtures.Authority.Probe,
    name: "chicago_authority_probe"
end

defmodule AshA2A.Chicago.Fixtures.Authority.VaultAgent do
  @moduledoc "Real `A2A.Agent` over `AshA2A.Chicago.Fixtures.Authority.Vault`."
  use AshA2A.Agent,
    resource_or_domain: AshA2A.Chicago.Fixtures.Authority.Vault,
    name: "chicago_authority_vault"
end
