defmodule AuthorityService.MtlsTest do
  use ExUnit.Case, async: true
  alias AuthorityService.{Listener, TestKit}
  import TestKit

  # Real certificate chains generated by :public_key (independent of the code under test).
  defp pki do
    k = [key: {:namedCurve, :secp256r1}, digest: :sha256]

    :public_key.pkix_test_data(%{
      server_chain: %{root: k, peer: k},
      client_chain: %{root: k, peer: k}
    })
  end

  defp pem(type, der), do: :public_key.pem_encode([{type, der, :not_encrypted}])

  defp files(dir, server_config, server_root) do
    {ktype, kder} = server_config[:key]

    File.write!(
      Path.join(dir, "srv.crt"),
      :public_key.pem_encode(
        for c <- [server_config[:cert] | server_root], do: {:Certificate, c, :not_encrypted}
      )
    )

    File.write!(Path.join(dir, "srv.key"), pem(ktype, kder))

    File.write!(
      Path.join(dir, "srv.ca"),
      :public_key.pem_encode(
        for c <- server_config[:cacerts], do: {:Certificate, c, :not_encrypted}
      )
    )

    [
      certfile: Path.join(dir, "srv.crt"),
      keyfile: Path.join(dir, "srv.key"),
      cacertfile: Path.join(dir, "srv.ca")
    ]
  end

  defp exchange(port, extra) do
    case :ssl.connect(
           ~c"localhost",
           port,
           [:binary, active: false, verify: :verify_none, versions: [:"tlsv1.3"]] ++ extra,
           3000
         ) do
      {:ok, s} ->
        body = Jason.encode!(%{"op" => "noop"})
        _ = :ssl.send(s, <<byte_size(body)::32, body::binary>>)

        res =
          with {:ok, <<len::32>>} <- :ssl.recv(s, 4, 2000),
               {:ok, b} <- :ssl.recv(s, len, 2000) do
            {:ok, Jason.decode!(b)}
          end

        :ssl.close(s)
        res

      err ->
        err
    end
  end

  test "TLS 1.3 mutual authentication: client with a CA-issued certificate is served; without one it is not" do
    ctx = start_issuer()
    conf = pki()
    tls = files(ctx.dir, conf[:server_config], conf[:client_config][:cacerts])
    {:ok, l} = Listener.start_link(issuer: ctx.issuer, transport: {:tls, 0, tls})
    port = Listener.port(l)

    # positive control: same channel, certificate presented -> typed reply
    cc = conf[:client_config]
    assert {:ok, %{"ok" => false, "refusal" => "unknown_op"}} = exchange(port, cc)

    # no client certificate -> never a reply
    refute match?({:ok, _}, exchange(port, []))
  end
end
