apiVersion: v1
kind: Service
metadata:
  name: actuator
  namespace: actuator-system
  labels:
    app.kubernetes.io/name: actuator
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: actuator
  ports:
    - name: mtls
      port: 8443
      targetPort: mtls
      protocol: TCP
