defmodule AshA2A.Test.Fixture.FreedomGym.PhaseAdmission do
  @moduledoc """
  Local, real, testable independent admission gate for the FreedomGym
  Facilitator's `:next_phase` action -- inserted between SELECT (the real
  `hddl_cli`-solved HDDL policy in
  `test/support/freedom_gym_meeting_plan.ex` chose this phase) and DO (the
  phase is returned to the caller / dispatched as an actuation result).

  ## Why this is a LOCAL EQUIVALENT, not literally beam4pm's module

  `beam4pm`'s real actuation admission gate is `BeamPM.Actuation`
  (`/Users/sac/beam4pm/lib/beam4pm_actuation.ex`, GENERATED by ggen_igniter
  from the admitted `bpma:AdmittedActuation` graph): a fail-closed
  `admission_verdict/1` that checks a validated action's `action_name`
  against a graph-derived `@admitted_actuations` allowlist map and binds the
  verdict into a `BeamPM.Types.PolicyDecision` struct before any execution
  step runs.

  `ash_a2a` is a separate, independently-deployed application (confirmed
  earlier in this repo's own history: ash_a2a cannot and does not depend on
  beam4pm as a library dependency -- there is no `{:beam4pm, ...}` mix dep
  and no compile-time coupling between the two apps' BEAM releases).
  Depending on `BeamPM.Actuation` directly from here would be a real
  cross-repo/cross-release dependency this codebase does not have and should
  not acquire just to get one admission check.

  So this module re-implements the SAME real shape locally, proportionate to
  this fixture's scope:

    * a fixed, real allowlist (`@admitted_phases`) -- the six real phase
      atoms the real `hddl_cli`-solved policy in
      `test/support/hddl/freedom_gym_meeting/domain.hddl` can ever produce
      (`open`, `trust_god`, `clean_house`, `help_others`, `fellowship`,
      `close`), not a hardcoded copy of beam4pm's own gym-op allowlist
      (different domain entirely -- meeting phases, not gym ops)
    * a fail-closed `admission_verdict/1`: anything not on the allowlist is
      refused, never silently let through
    * a `decision/1` helper that binds the verdict into a small, real,
      inspectable decision map (this fixture's local analog of
      `BeamPM.Types.PolicyDecision` -- no ontology-generated struct exists
      here, so a plain map with the same `verdict`/`reason` shape is used)

  This is deliberately NOT beam4pm's `BeamPM.Actuation` Reactor pipeline (no
  gym bridge, no OCEL receipt events, no hash-chained receipts) -- only the
  one real property this task requires: an independent SELECT-vs-DO
  admission check exists and is fail-closed, exercised by a real Chicago
  test below.
  """

  @admitted_phases MapSet.new([
                      :open,
                      :trust_god,
                      :clean_house,
                      :help_others,
                      :fellowship,
                      :close
                    ])

  @doc "The real admitted-phase allowlist enforced by this gate."
  @spec admitted_phases() :: MapSet.t(atom())
  def admitted_phases, do: @admitted_phases

  @doc """
  Fail-closed admission verdict for one candidate phase atom (as popped from
  the real HDDL-solved plan by
  `AshA2A.Test.Fixture.FreedomGym.MeetingPlan.next_phase/1`).

  `{:admitted, phase}` only when `phase` is a member of the real
  `@admitted_phases` allowlist; `{:refused, reason}` for anything else
  (including a plan producing a phase atom this gate was never told about --
  the exact "newest code is least gated" gap this module exists to close).
  """
  @spec admission_verdict(atom()) :: {:admitted, atom()} | {:refused, String.t()}
  def admission_verdict(phase) when is_atom(phase) do
    if MapSet.member?(@admitted_phases, phase) do
      {:admitted, phase}
    else
      {:refused,
       "phase #{inspect(phase)} is not an admitted FreedomGym meeting phase " <>
         "(local allowlist: #{inspect(MapSet.to_list(@admitted_phases))})"}
    end
  end

  @doc """
  Runs `admission_verdict/1` and returns the typed pass/refuse result the
  Facilitator action's `:next_phase` run function wires against:
  `{:ok, phase}` on admission, `{:error, {:not_admitted, phase}}` on refusal
  (never a silently-actuated unadmitted phase).
  """
  @spec admit(atom()) :: {:ok, atom()} | {:error, {:not_admitted, atom()}}
  def admit(phase) when is_atom(phase) do
    case admission_verdict(phase) do
      {:admitted, ^phase} -> {:ok, phase}
      {:refused, _reason} -> {:error, {:not_admitted, phase}}
    end
  end

  @doc """
  Binds an admission verdict into a small, real, inspectable decision map --
  this fixture's local analog of `BeamPM.Types.PolicyDecision` (verdict +
  reason), without pulling in beam4pm's ontology-generated struct.
  """
  @spec decision(atom()) :: %{verdict: :admitted | :refused, phase: atom(), reason: String.t()}
  def decision(phase) when is_atom(phase) do
    case admission_verdict(phase) do
      {:admitted, ^phase} ->
        %{verdict: :admitted, phase: phase, reason: "phase #{inspect(phase)} is admitted"}

      {:refused, reason} ->
        %{verdict: :refused, phase: phase, reason: reason}
    end
  end
end
