defmodule AshA2A.CapabilityIndex.AgentCardBuilder do
  @moduledoc """
  Deterministically projects a derived Ash capability index into
  `A2A.AgentCard.t()`.

  Skill ids come from the canonical `{resource, action}` identity generated by
  `AshA2A.CapabilityIndex.Compiler`; names/descriptions/tags may carry residual
  A2A overrides. Arguments are always introspected from the real Ash action.
  """

  @type skill :: AshA2A.Skill.t()

  @spec build_agent_card([skill()], keyword()) :: A2A.AgentCard.t()
  def build_agent_card(skills, opts \\ []) when is_list(skills) do
    url = Keyword.get(opts, :url, "http://localhost:4000")
    ordered_skills = Enum.sort_by(skills, &skill_id/1)

    %A2A.AgentCard{
      name: Keyword.get(opts, :name, "ash_a2a_agent"),
      description:
        Keyword.get(
          opts,
          :description,
          "Ash-backed A2A agent exposing #{length(ordered_skills)} skill(s)."
        ),
      url: url,
      version: Keyword.get(opts, :version, "0.1.0"),
      skills: Enum.map(ordered_skills, &build_agent_card_skill/1),
      provider: Keyword.get(opts, :provider),
      security_schemes: Keyword.get(opts, :security_schemes, %{}),
      security: Keyword.get(opts, :security, []),
      supported_interfaces:
        Keyword.get(opts, :supported_interfaces, [default_supported_interface(url)])
    }
  end

  @spec default_supported_interface(String.t()) :: A2A.AgentCard.supported_interface()
  defp default_supported_interface(url) do
    %{url: url, protocol_binding: "JSONRPC", protocol_version: "0.3.0"}
  end

  @spec build_agent_card_skill(skill()) :: A2A.AgentCard.skill()
  defp build_agent_card_skill(%{resource: resource, action: action} = skill) do
    real_action = Ash.Resource.Info.action(resource, action)

    %{
      id: skill_id(skill),
      name: to_string(skill.name || action),
      description: skill.description || skill_description(resource, action, real_action),
      tags: skill.tags || skill_tags(action, real_action)
    }
  end

  defp skill_id(%{id: id}) when is_binary(id), do: id

  defp skill_id(%{resource: resource, action: action}) do
    AshA2A.CapabilityIndex.Compiler.capability_id(resource, action)
  end

  defp skill_tags(action, nil), do: [to_string(action)]

  defp skill_tags(_action, real_action) do
    [real_action.type |> to_string()]
    |> Kernel.++(Enum.map(input_names(real_action), &to_string/1))
    |> Enum.uniq()
  end

  defp skill_description(resource, action, nil) do
    "Dispatches to #{inspect(resource)}.#{action}/*"
  end

  defp skill_description(resource, _action, real_action) do
    inputs = input_names(real_action)

    inputs_clause =
      case inputs do
        [] -> "no arguments"
        names -> "arguments: #{Enum.map_join(names, ", ", &to_string/1)}"
      end

    base =
      case real_action.description do
        nil -> "#{real_action.type} action #{inspect(real_action.name)} on #{inspect(resource)}"
        description -> description
      end

    "#{base} (#{inputs_clause})"
  end

  defp input_names(real_action) do
    argument_names =
      real_action
      |> Map.get(:arguments, [])
      |> Enum.filter(&Map.get(&1, :public?, true))
      |> Enum.map(& &1.name)

    accept_names = real_action |> Map.get(:accept) |> List.wrap()
    argument_names ++ accept_names
  end
end
