# SPDX-FileCopyrightText: 2026 ash_a2a contributors <https://github.com/seanchatmangpt/ash_a2a/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshA2A.CapabilityIndex.AgentCardBuilder do
  @moduledoc """
  Deterministically projects a derived Ash capability index into
  `AshA2A.Protocol.AgentCard.t()`.

  Skill ids come from the canonical `{resource, action}` identity generated by
  `AshA2A.CapabilityIndex.Compiler`; names/descriptions/tags may carry residual
  A2A overrides. Arguments are always introspected from the real Ash action.

  Per-skill `input_modes`/`output_modes` (spec `AgentSkill` fields 6/7) are
  projected via the `:skills_opts` build option — a map keyed by skill
  capability id or declared name whose values carry `:input_modes`/
  `:output_modes` lists. A skill with no entry (or nil values) inherits the
  card-level defaults. `AshA2A.Info.agent_card/2` forwards `:skills_opts`.

  `supported_interfaces` resolve in declaration order:

    1. an explicit `:supported_interfaces` opt — the manual override surface
       (e.g. the demo's hand-listed JSONRPC/HTTP+JSON/GRPC triple);
    2. the subject domain's declared `AshA2A.Domain` transport mounts —
       injected by `AshA2A.Info.agent_card/2` via
       `AshA2A.Domain.Info.supported_interfaces/1`: one entry per declared
       mount, `url` = `transport.base_url` joined with the mount path,
       `protocol_binding` mapped by `AshA2A.Domain.Mount.protocol_binding/1`;
    3. the legacy single-JSONRPC default at the card `url`.
  """

  @type skill :: AshA2A.Skill.t()

  # Single source of protocol constants for the card projection: the A2A
  # protocol version comes from `AshA2A.Protocol.Version` (spec v1.0,
  # sections 4.4/8.2), never a local literal. The codec
  # (`AshA2A.Protocol.JSON.encode_agent_card/2`) only falls back to its own
  # legacy default when a card struct carries no `supported_interfaces`;
  # because `build_agent_card/2` below always emits a fully-populated,
  # non-empty list normalized to these constants, the served card can never
  # fall back to the codec's legacy default.
  @protocol_binding "JSONRPC"

  @doc """
  The A2A protocol version advertised in every emitted supported_interface.
  Delegates to `AshA2A.Protocol.Version.protocol_version/0`.

      iex> AshA2A.CapabilityIndex.AgentCardBuilder.protocol_version()
      "1.0"
  """
  @spec protocol_version() :: String.t()
  def protocol_version, do: AshA2A.Protocol.Version.protocol_version()

  @doc """
  The protocol binding advertised in every emitted supported_interface.

      iex> AshA2A.CapabilityIndex.AgentCardBuilder.protocol_binding()
      "JSONRPC"
  """
  @spec protocol_binding() :: String.t()
  def protocol_binding, do: @protocol_binding

  @spec build_agent_card([skill()], keyword()) :: AshA2A.Protocol.AgentCard.t()
  def build_agent_card(skills, opts \\ []) when is_list(skills) do
    url = Keyword.get(opts, :url, "http://localhost:4000")
    ordered_skills = Enum.sort_by(skills, &skill_id/1)
    skills_opts = Keyword.get(opts, :skills_opts, %{})

    %AshA2A.Protocol.AgentCard{
      name: Keyword.get(opts, :name, "ash_a2a_agent"),
      description:
        Keyword.get(
          opts,
          :description,
          "Ash-backed A2A agent exposing #{length(ordered_skills)} skill(s)."
        ),
      url: url,
      version: Keyword.get(opts, :version, "0.1.0"),
      skills: Enum.map(ordered_skills, &build_agent_card_skill(&1, skills_opts)),
      provider: Keyword.get(opts, :provider),
      capabilities: Keyword.get(opts, :capabilities, default_capabilities()),
      security_schemes: Keyword.get(opts, :security_schemes, %{}),
      security: Keyword.get(opts, :security, []),
      supported_interfaces:
        normalize_supported_interfaces(Keyword.get(opts, :supported_interfaces), url)
    }
  end

  # CONF-06: the struct advertises what the runtime really serves --
  # `message/stream` works for every skill through `AshA2A.Transport.Plug`,
  # while push notifications, state-transition history and the extended card
  # are not served, so they are advertised `false` rather than omitted.
  @spec default_capabilities() :: map()
  defp default_capabilities do
    %{
      streaming: true,
      push_notifications: false,
      state_transition_history: false,
      extended_agent_card: false
    }
  end

  @spec default_supported_interface(String.t()) :: AshA2A.Protocol.AgentCard.supported_interface()
  defp default_supported_interface(url) do
    %{
      url: url,
      protocol_binding: @protocol_binding,
      protocol_version: AshA2A.Protocol.Version.protocol_version()
    }
  end

  # The card is the deterministic projection of the index, so whatever
  # interface list reaches the card must be complete: every entry carries a
  # url (defaulting to the builder/opts url) and these protocol constants.
  # This is what makes the card-field-wins resolution in
  # `AshA2A.Protocol.JSON.encode_agent_card/2` resolve at the card level and
  # never fall through to the codec's legacy "2.0" default.
  @spec normalize_supported_interfaces([map()] | nil, String.t()) :: [
          AshA2A.Protocol.AgentCard.supported_interface()
        ]
  defp normalize_supported_interfaces(nil, url), do: [default_supported_interface(url)]

  defp normalize_supported_interfaces(interfaces, url) when is_list(interfaces) do
    case Enum.reject(interfaces, &is_nil/1) do
      [] -> [default_supported_interface(url)]
      non_empty -> Enum.map(non_empty, &normalize_supported_interface(&1, url))
    end
  end

  defp normalize_supported_interface(interface, url) when is_map(interface) do
    %{
      url: Map.get(interface, :url, Map.get(interface, "url")) || url,
      protocol_binding:
        Map.get(interface, :protocol_binding, Map.get(interface, "protocolBinding")) ||
          @protocol_binding,
      # The protocol version is not caller-overridable: every emitted
      # interface carries the single-source-of-truth version from
      # `AshA2A.Protocol.Version` (spec v1.0, sections 4.4/8.2).
      protocol_version: AshA2A.Protocol.Version.protocol_version()
    }
  end

  @spec build_agent_card_skill(
          skill(),
          %{optional(String.t() | atom()) => keyword() | map()}
        ) :: AshA2A.Protocol.AgentCard.skill()
  defp build_agent_card_skill(%{resource: resource, action: action} = skill, skills_opts) do
    real_action = Ash.Resource.Info.action(resource, action)

    mode_opts = skill_mode_opts(skill, skills_opts)

    input_modes = mode_opt(mode_opts, :input_modes) || Map.get(skill, :input_modes)
    output_modes = mode_opt(mode_opts, :output_modes) || Map.get(skill, :output_modes)
    # Spec AgentSkill field 8 (securityRequirements): same resolution order —
    # builder-level skills_opts entry first, then the skill struct's own
    # field; nil/[] = inherit card-level security (omitted from the wire).
    security_requirements =
      mode_opt(mode_opts, :security_requirements) || Map.get(skill, :security_requirements)

    base = %{
      id: skill_id(skill),
      name: to_string(skill.name || action),
      description: skill.description || skill_description(resource, action, real_action),
      tags: skill.tags || skill_tags(action, real_action)
    }

    base
    |> maybe_put_skill_mode(:input_modes, input_modes)
    |> maybe_put_skill_mode(:output_modes, output_modes)
    |> maybe_put_skill_mode(:security_requirements, security_requirements)
  end

  # Per-skill `inputModes`/`outputModes` projection (spec AgentSkill fields
  # 6/7, OPTIONAL override of the card defaults). Resolution order:
  #
  #   1. an explicit `:skills_opts` entry for this skill — the builder-level
  #      override surface, keyed by the skill's capability `id`
  #      ("<Resource>.<action>") or its declared `name` (atom or binary
  #      spelling accepted);
  #   2. the skill struct's own `:input_modes`/`:output_modes` fields (read
  #      with `Map.get/2` so a skill shape that does not carry the fields
  #      behaves exactly like `nil`);
  #   3. `nil` — key omitted from the emitted card skill, meaning the skill
  #      inherits the card-level `default_input_modes`/`default_output_modes`.
  #
  # There is no DSL or Ash-action-native mode hint today
  # (`AshA2A.Skill` carries no mode fields and the `a2a do skill ... end`
  # schema has no mode options), so surface (1) is the only way a user can
  # declare per-skill modes through the real builder path
  # (`AshA2A.Info.agent_card/2` forwards `:skills_opts`).
  defp skill_mode_opts(skill, skills_opts) when is_map(skills_opts) and skills_opts != %{} do
    Enum.find_value([skill_id(skill), skill.name, stringify_name(skill.name)], fn key ->
      Map.get(skills_opts, key)
    end)
  end

  defp skill_mode_opts(_skill, _skills_opts), do: nil

  defp mode_opt(nil, _key), do: nil

  defp mode_opt(opts, key) when is_map(opts) do
    mode_opt_value(Map.get(opts, key))
  end

  defp mode_opt(opts, key) when is_list(opts), do: mode_opt_value(Keyword.get(opts, key))

  defp mode_opt_value(nil), do: nil
  defp mode_opt_value(modes), do: modes

  defp stringify_name(nil), do: nil
  defp stringify_name(name) when is_atom(name), do: Atom.to_string(name)
  defp stringify_name(name) when is_binary(name), do: name

  defp maybe_put_skill_mode(map, _key, nil), do: map
  defp maybe_put_skill_mode(map, key, modes), do: Map.put(map, key, modes)

  defp skill_id(%{id: id}) when is_binary(id), do: id

  defp skill_id(%{resource: resource, action: action}) do
    AshA2A.CapabilityIndex.Compiler.capability_id(resource, action)
  end

  defp skill_tags(action, nil), do: [to_string(action)]

  defp skill_tags(_action, real_action) do
    [real_action.type |> to_string()]
    |> Kernel.++(Enum.map(input_names(real_action), &to_string/1))
    |> Enum.uniq()
  end

  defp skill_description(resource, action, nil) do
    "Dispatches to #{inspect(resource)}.#{action}/*"
  end

  defp skill_description(resource, _action, real_action) do
    inputs = input_names(real_action)

    inputs_clause =
      case inputs do
        [] -> "no arguments"
        names -> "arguments: #{Enum.map_join(names, ", ", &to_string/1)}"
      end

    base =
      case real_action.description do
        nil -> "#{real_action.type} action #{inspect(real_action.name)} on #{inspect(resource)}"
        description -> description
      end

    "#{base} (#{inputs_clause})"
  end

  defp input_names(real_action) do
    argument_names =
      real_action
      |> Map.get(:arguments, [])
      |> Enum.filter(&Map.get(&1, :public?, true))
      |> Enum.map(& &1.name)

    accept_names = real_action |> Map.get(:accept) |> List.wrap()
    argument_names ++ accept_names
  end
end
