defmodule SwarmNode.EchoAgent do
  @moduledoc """
  Real, supervised `A2A.Agent` GenServer for `SwarmNode.Echo`, generated by
  `AshA2A.Agent` (the exact real macro every other consumer in this
  codebase uses -- `lib/ash_a2a/agent.ex`). Registered locally under this
  module's own name (`A2A.Agent`'s `start_link/1` default) on whichever
  pod/node it runs on; a peer node reaches it with real distributed Erlang
  addressing: `GenServer.call({SwarmNode.EchoAgent, target_node}, ...)`
  (equivalently `SwarmNode.EchoAgent.call({SwarmNode.EchoAgent,
  target_node}, message)`), never through any HTTP surface -- this repo's
  `A2A.Agent`/`AshA2A.Dispatcher` path is pure BEAM message passing.
  """

  use AshA2A.Agent, resource_or_domain: SwarmNode.Echo
end
