defmodule SwarmNode.EchoAgent do
  @moduledoc """
  Real, supervised `AshA2A.Protocol.Agent` GenServer for `SwarmNode.Echo`, generated by
  `AshA2A.Agent` (the exact real macro every other consumer in this
  codebase uses -- `lib/ash_a2a/agent.ex`). Registered locally under this
  module's own name (`AshA2A.Protocol.Agent`'s `start_link/1` default) on whichever
  pod/node it runs on; a peer node reaches it with real distributed Erlang
  addressing: `GenServer.call({SwarmNode.EchoAgent, target_node}, ...)`
  (equivalently `SwarmNode.EchoAgent.call({SwarmNode.EchoAgent,
  target_node}, message)`); the opt-in HTTP surface is `SwarmNode.A2ARouter`.

  Authentication: `ash_a2a` refuses unauthenticated callers by default
  (`:require_authenticated_caller`). The BEAM-dispatch probe carries no A2A
  auth identity; its caller is authenticated at the transport instead
  (distribution over mutually-authenticated TLS, rel/ssl_dist.conf). So only
  the `:observe`-only, side-effect-free `ping` skill is declared public; any
  future `:change`/`:external_do` skill stays behind authentication and the
  authority broker.
  """

  use AshA2A.Agent, resource_or_domain: SwarmNode.Echo, public_skills: [:ping]
end
